name: Triage add issue/PR to project

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
jobs:
  add-to-triage-project:
    name: Add to triage project
    runs-on: ubuntu-latest
    steps:
      - name: is-collaborator
        env:
          ORGANIZATION: 'bellamae'
          REPOSITORY: 'actions-test'
          USER: ${{ github.event.issue.user.login }}
        run: |
          gh api graphql -f query='
            query($org: String!, $repo: String!, $user: String!) {
              repository(owner: $org, name: $repo) {
                collaborators(query: $user, first: 1) {
                  totalCount
                }
              }
            } ' -f org=$ORGANIZATION -f repo=$REPOSITORY -f user=$USER > collaborators.json

          echo 'IS_COLLABORATOR='$(jq -r '.data.repository.collaborators.totalCount' collaborators.json) >> $GITHUB_ENV
      - uses: actions/add-to-project@v0.3.0
        id: add-to-triage-project
        # only add issues/prs from non-collaborators
        if: ${{ env.IS_COLLABORATOR == 1 }}
        with:
          project-url: https://github.com/orgs/konabell/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
      - name: update issue in project
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            query($org: String!, $project: Int!) {
              organization(login: $org) {
                projectV2(number: 1) {
                  id
                  field(name: "Date Added to Triage Backlog") {
                    ... on ProjectV2Field {
                      id
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F project=$PROJECT_NUMBER > project_data.json

          project_id = $(jq -r '.data.organization.projectV2 | .id' project_data.json)
          field_id = $(jq -r '.data.organization.projectV2 | .field.id' project_data.json)

          gh api graphql -f query='
            mutation($project:ID!, $item:ID!, $field:ID!) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $project
                  itemId: $item
                  fieldId: $status_field
                  value: { 
                    singleSelectOptionId: $routed_option
                  }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }' -f project=project_id -f item=$steps.add-to-triage-project.outputs.itemId -f field=field_id
